__title__ = 'BearSki'
__description__ = 'There is a toolbox for autotest'
__url__ = 'https://github.com/Sirius1942/BearSki'
__version__ = '1.5.0'
__author__ = 'chenjiusi'
__author_email__ = 'chen6_9@163.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2020 QiYi Technology'