runner:  #设置用例执行器
  name: PyTestRunner
  commands:
    - -s
#    - -o log_cli=true
#    - -o log_cli_level=ERROR
    - utest/testcase/test_send.py
unittestcase:
  mode: onecase
case:
  path: utest.testcase.atest_api_users.atest_api_users.case_api_users
  name: ""
ski_filepath: SkiSetting.py
report:
  mode: html
  path: ./utest/report/report1.html
  addtime.now: true
auto:
  case_path: utest/testdata/model
  model_path: utest/testdata/model
log:
  file_path: utest/log/log.log
  level: INFO